In [ ]:
import pandas as pd

df = pd.read_csv("../data/raw/btc_1d_data_2018_to_2025.csv")

df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3089 entries, 0 to 3088
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Open time                     3089 non-null   object
 1   Open                          3089 non-null   float64
 2   High                          3089 non-null   float64
 3   Low                           3089 non-null   float64
 4   Close                         3089 non-null   float64
 5   Volume                        3089 non-null   float64
 6   Close time                    3089 non-null   object
 7   Quote asset volume            3089 non-null   float64
 8   Number of trades              3089 non-null   int64
 9   Taker buy base asset volume   3089 non-null   float64
 10  Taker buy quote asset volume  3089 non-null   float64
 11  Ignore                        3089 non-null   int64
dtypes: float64(8), int64(2), object(2)
memory usage: 289.7+ KB

,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
count,3089.000000,3089.000000,3089.000000,3089.000000,3089.000000,3.089000e+03,3.089000e+03,3089.000000,3.089000e+03,3089.0
mean,39287.812415,40012.310408,38513.420275,39318.444497,61314.590240,1.688531e+09,1.768101e+06,30461.854843,8.348284e+08,0.0
std,32550.419673,32915.738942,32173.333279,32570.465481,77087.408455,1.930051e+09,2.104859e+06,38367.966353,9.595087e+08,0.0
min,3211.710000,3276.500000,3156.260000,3211.720000,165.221800,1.177017e+07,1.241700e+04,73.680390,6.532639e+06,0.0
25%,9700.420000,9937.000000,9420.750000,9700.420000,23284.041191,3.378388e+08,3.846780e+05,11709.621740,1.686756e+08,0.0
50%,29233.200000,29739.250000,28839.210000,29281.090000,39157.922565,1.046828e+09,1.032493e+06,19603.523572,5.082088e+08,0.0
75%,62135.460000,63469.130000,60650.000000,62160.490000,65171.504046,2.309514e+09,2.151711e+06,32338.074002,1.146732e+09,0.0
max,124658.540000,125082.270000,124600.000000,125046.940000,760705.362783,1.746531e+10,1.522359e+07,374775.574085,8.783916e+09,0.0

In [8]:
df.describe()

,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
count,3089.000000,3089.000000,3089.000000,3089.000000,3089.000000,3.089000e+03,3.089000e+03,3089.000000,3.089000e+03,3089.0
mean,39287.812415,40012.310408,38513.420275,39318.444497,61314.590240,1.688531e+09,1.768101e+06,30461.854843,8.348284e+08,0.0
std,32550.419673,32915.738942,32173.333279,32570.465481,77087.408455,1.930051e+09,2.104859e+06,38367.966353,9.595087e+08,0.0
min,3211.710000,3276.500000,3156.260000,3211.720000,165.221800,1.177017e+07,1.241700e+04,73.680390,6.532639e+06,0.0
25%,9700.420000,9937.000000,9420.750000,9700.420000,23284.041191,3.378388e+08,3.846780e+05,11709.621740,1.686756e+08,0.0
50%,29233.200000,29739.250000,28839.210000,29281.090000,39157.922565,1.046828e+09,1.032493e+06,19603.523572,5.082088e+08,0.0
75%,62135.460000,63469.130000,60650.000000,62160.490000,65171.504046,2.309514e+09,2.151711e+06,32338.074002,1.146732e+09,0.0
max,124658.540000,125082.270000,124600.000000,125046.940000,760705.362783,1.746531e+10,1.522359e+07,374775.574085,8.783916e+09,0.0